/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Prac1                                  */
/*      FILE         :  Prac1.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   


/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
	static int initialized;
	if (! initialized)
	{
		typedef void (*pfunc) ();
		extern pfunc __ctors[];
		extern pfunc __ctors_end[];
		pfunc *p;

		initialized = 1;
		for (p = __ctors_end; p > __ctors; )
			(*--p) ();

	}
}
#endif 

extern switchLEDon();
extern switchLEDoff();
extern toggleLED();

void delay(unsigned long time)
{
	/*
We leave this piece of code in C for now,
as it is complex to rewrite in asm.
	 */
	unsigned long counter=0;
	for(counter=0; counter<time; counter++)
	{
		asm("nop"); // assembly for No Operation
	}
}

int main(void)
{
	// Set Port 7, Pin 7 as output
	PM7=0x7F;
	// main loop
	while (1) {
		toggleLED();
		delay(80000UL);
	}
}
