/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Prac7                                  */
/*      FILE         :  Prac7.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   


/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
	static int initialized;
	if (! initialized)
	{
		typedef void (*pfunc) ();
		extern pfunc __ctors[];
		extern pfunc __ctors_end[];
		pfunc *p;

		initialized = 1;
		for (p = __ctors_end; p > __ctors; )
			(*--p) ();

	}
}
#endif 

#include "iodefine.h"

extern void toggleLED();

extern int calculateUniqueNumber(int, int, int, int, int, int, int, int);
extern int generate_checksum(char*);
extern int validate_checksum(int);
extern void bubble_sort(char*);

int calculate_unique_number_in_c(int, int, int, int, int, int, int, int);
int generate_checksum_in_c(char*);
int validate_checksum_in_c(int);
void bubble_sort_in_c(char*);

int main(void)
{
	// variable definitions
	char studentNr[] = "18273645";
	int uniqueNumber = 0;
	int checksum = 0;
	int valid = 0;

	// set up LED pin as an output
	PM7 = 0b01111111;

	// Toggle LED, execute function, repeat indefinitely. This will cause the LED to flash. Measure the flashing period.
	while (1)
	{
		// toggle the LED so that we can see the timing

		//TODO: enable the function we want to time by uncommenting the appropriate lines
		/*uniqueNumber = calculateUniqueNumber(1, 8, 2, 7, 3, 6, 4, 5);*/
		toggleLED();


		/*checksum = generate_checksum(studentNr);
		toggleLED();*/


		/*valid = validate_checksum(121);
		toggleLED();*/


		/*bubble_sort(studentNr);
		toggleLED();*/


		/*calculate_unique_number_in_c(1, 8, 2, 7, 3, 6, 4, 5);
		toggleLED();*/


		/*generate_checksum_in_c(studentNr);
		toggleLED();*/


		/*validate_checksum_in_c(121);
		toggleLED();*/


		/*bubble_sort_in_c(studentNr);
		toggleLED();*/
	}
}


// Student number functions
int calculate_unique_number_in_c(int a, int b, int c, int d, int e, int f, int g, int h)
{
	//TODO: write your code here
	int smallTot = 0, bigTot = 0, Tot = 0;
	char num[] = {a, b, c, d, e, f, g, h};
	bubble_sort_in_c(num);

	smallTot = num[0] + num[1] + num[2] + num[3];
	bigTot = num[4] + num[5] + num[6] + num[7];

	Tot = bigTot * smallTot;
	return Tot;
}

int generate_checksum_in_c(char* studentNumber)
{
	//TODO: write your code here
	int i;
	int N = 8;
	int tot = 0;
	int tempNum = 0;

	for(i = 0; i < N; i++)
	{
		tempNum = studentNumber[i] - 48;
		tot += tempNum * (8 - i);
	}

	return tot;
}

int validate_checksum_in_c(int checksum)
{
	//TODO: write your code here
	return (checksum % 11)? 0 : 1;
}

void bubble_sort_in_c(char* studentNumber)
{
	//TODO: write your code here
	int i;
	int j;
	int N = 8;

	for(i = 0; i < N; i++)
	{
		for(j = 0; j < N; j++)
		{
			if(studentNumber[i] > studentNumber[j])
				swap(i, j, studentNumber);
		}
	}
}

void swap(int first, int second, char* array)
{
	char temp = array[first];
	array[first] = array[second];
	array[second] = temp;
}
