/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Prac2                                  */
/*      FILE         :  Prac2.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   


/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/
/*
 * Author: Elan van Biljon - 18384439
 */

#include "iodefine.h"
#include "stdlib.h"
#include "stdio.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
	static int initialized;
	if (! initialized)
	{
		typedef void (*pfunc) ();
		extern pfunc __ctors[];
		extern pfunc __ctors_end[];
		pfunc *p;

		initialized = 1;
		for (p = __ctors_end; p > __ctors; )
			(*--p) ();

	}
}
#endif 

int adder(int a, int b, int c, int d)
{
	return adder2(adder2(a, b), adder2(c, d));
}

extern int adder2(int a, int b);
extern int adder4(int a, int b, int c, int d);

extern char* changecase(char* sentance);
char sentance[] = "mOET VERKIESLIK TEEN vRYDAG @ 17:00 VOLTOOI WEES![{'ok'}]";

int main(void)
{
 	int answer = 0;
	char* sent;
	//int count = 0;
	while(1)
	{
		answer = adder(10, answer, 4, 4);
		changecase(sentance);
		sent = sentance;
	}

	return 0;
}
