/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Prac5                                  */
/*      FILE         :  Prac5.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   
                                                                                            
                                                                                            
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

extern void sort(char * sent);
extern int populate_addresses(int start, int end, char num);
extern int find_number(int start, int end, char num);

int main(void)
{
    // TODO: add application code here
	//char sent[] = "10234d457a6#4@6$786d9}1@50";
	int start = 5000;
	int end = 5020;
	int actual = 0;
	int count = 0;
	char num = '2';

    while (1)
    {
    	//sort(sent);

    	actual = populate_addresses(start, end, num);
    	count = find_number(start, end, num);
    }
  return 0;
}
