/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Prac4                                  */
/*      FILE         :  Prac4.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   
                                                                                            
                                                                                            
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void)
{
    // TODO: add application code here

	extern int calculateUniuqeNumber(int a, int b, int c, int d, int e, int f, int g, int h);
	extern int generate_checksum(char* c);
	extern int validate_checksum(int a);

    while (1) {
    	int uniqueNumber = calculateUniqueNumber(1, 8, 3, 8, 4, 4, 3, 9);
    	int checkSum = generate_checksum("18384439");
    	int valid = validate_checksum(checkSum);
    	int notValid = validate_checksum(checkSum+1);
    }
  return 0;
}
