/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Prac3                                  */
/*      FILE         :  Prac3.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   


/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 10/09/2013                                        */
/************************************************************************/

#include "iodefine.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
	static int initialized;
	if (! initialized)
	{
		typedef void (*pfunc) ();
		extern pfunc __ctors[];
		extern pfunc __ctors_end[];
		pfunc *p;

		initialized = 1;
		for (p = __ctors_end; p > __ctors; )
			(*--p) ();

	}
}
#endif 

extern char* reverse(char* sent);
extern char* reverse2(char* sent);

extern int calculate(char o, int a, int b);

char sentance[] = "sdrawkcab ton si siht";

int main(void)
{
	// TODO: add application code here
	char* correctSent;

	int added = 0;
	int subed = 0;
	int muled = 0;

	while (1)
	{
		reverse(sentance);
		correctSent = sentance;

		added = calculate('+',5,16);
		subed = calculate('-',42,13);
		muled = calculate('*',2,7);
	}
	return 0;
}
